# Generated by Django 3.0.5 on 2020-04-08 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
