# Generated by Django 3.0.5 on 2020-04-09 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200409_0036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due'], 'permissions': (('can_mark_returned', 'Can set book as returned'),)},
        ),
    ]
